spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/rest_api
        username: udemy
        password: admin
    jpa:
        hibernate:
          ddl-auto: update
        properties: 
          show-sql: true
