cors:
  originPatterns: http://localhost:4200,http://localhost:8080,http://127.0.0.1:8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/api_rest
        username: student
        password: admin
    jpa:
        hibernate:
          ddl-auto: none
springdoc:  
  pathsToMatch: "/api/**/v1/**"
  swagger-ui:
    use-root-path: true
  
